# Generated by Django 4.2 on 2023-04-21 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('questionId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Respondent',
            fields=[
                ('respondentId', models.AutoField(primary_key=True, serialize=False)),
                ('phoneNumber', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('surveyId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('responseId', models.AutoField(primary_key=True, serialize=False)),
                ('response', models.CharField(max_length=50)),
                ('questionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.question')),
                ('respondentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.respondent')),
                ('surveyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey')),
            ],
        ),
        migrations.AddField(
            model_name='respondent',
            name='surveyId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey'),
        ),
        migrations.AddField(
            model_name='question',
            name='surveyId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.survey'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('answerId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('questionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.question')),
            ],
        ),
    ]
