# Generated by Django 4.2 on 2023-04-21 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='response',
            name='response',
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(default='checkbox', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='answerId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='survey.answer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='response',
            name='isChecked',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='questionId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='response',
            name='responseId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='survey',
            name='surveyId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
