# Generated by Django 4.2 on 2023-04-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_remove_response_response_question_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='isChecked',
            new_name='isCheck',
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('checkbox', 'Checkbox'), ('radio', 'Radio'), ('select', 'Select')], max_length=10),
        ),
    ]
