# Generated by Django 4.2 on 2023-04-21 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_rename_ischecked_response_ischeck_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soron',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
