# Generated by Django 4.2 on 2023-04-23 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_soron'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questionId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='response',
            name='responseId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='soron',
            name='uid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='survey',
            name='surveyId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
