# Generated by Django 4.2 on 2023-04-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0005_alter_question_questionid_alter_response_responseid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="response",
            name="isCheck",
        ),
        migrations.AddField(
            model_name="answer",
            name="isCheck",
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
